### ISSUE TITLE
Can't launch the program

### ISSUE THREAD

**Issue by ilovefreesw** [dkgv/pinpoint#108]
![image](https://user-images.githubusercontent.com/77317006/118808169-cdc1d600-b8c6-11eb-8467-b8949fbf1fb9.png)

Getting .Net Core issue. I downloaded the .Net Core runtime and installed it but this error persists.

**Comment by sunero4** [comment]
That is strange - we had actually missed the fact that having .NET Core installed was a requirement, so we have plans of creating self-contained releases from now on, so that installing the runtime separately is not a requirement :)

**Comment by dkgv** [comment]
(facepalm, accidentally deleted @sunero4's comment)

Starting from the next version we'll be building and releasing a self-contained version with all dependencies bundled.

**Comment by ilovefreesw** [comment]
How can I make it run now ? Any ideas ?
