### ISSUE TITLE
Not working on UHD/4K 288 DPI

### ISSUE THREAD

**Issue by stax76** [dkgv/pinpoint#119]
```C#
        public void OnToggleVisibility([CanBeNull] object sender, HotkeyEventArgs e)
        {
            if (App.Current.SettingsWindow.Visibility == Visibility.Visible)
            {
                return;
            }

            if (Visibility == Visibility.Visible)
            {
                Hide();
            }
            else
            {
                var screen = Screen.FromPoint(System.Windows.Forms.Cursor.Position);
                //Left = (screen.Bounds.Left + screen.Bounds.Width / 2 - Width / 2) + _offsetFromDefaultX;
                //Top = (screen.Bounds.Top + screen.Bounds.Height / 5) + _offsetFromDefaultY;

                Show();
                Activate();
                TxtQuery.Focus();
                TxtQuery.SelectAll();
            }
        }
```

**Comment by sunero4** [comment]
Could you please elaborate what it is that is not working? I am not sure I understand from the code sample

**Comment by stax76** [comment]
The Window is off-screen, it's not visible at all.

**Comment by sunero4** [comment]
Huh, that's strange. We'll investigate. Is there a reason the two lines with Left and Top are commented in the code snippet you posted? I could see they aren't commented on the master branch

**Comment by stax76** [comment]
These 2 lines is where the bug is at, you are mixing pixel with virtual pixel, note that I use 288 DPI.

**Comment by dkgv** [comment]
I haven't had time to properly investigate this so I'm adding the "help wanted" tag in case anyone reading this wants to help out.
