### ISSUE TITLE
Symentec Endpoint Protection detects Pinpoint as virus

### ISSUE THREAD

**Issue by balaji-ch** [dkgv/pinpoint#131]
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\Users\xxx\Desktop\pinpoint-0.2.4\Pinpoint.exe
Location: Quarantine
Computer: xxx
User:   xxx
Action taken: Quarantine succeeded
Date found: Friday, January 7, 2022  9:40:48 AM

**Comment by dkgv** [comment]
I just looked up "WS.Reputation.1" and by Nortons own definition it seems to be a file ranking metric of sorts more so than a virus class. See https://community.norton.com/en/forums/clarification-wsreputation1-detection

You are of course always welcome to clone the repository and build the project yourself.

**Comment by balaji-ch** [comment]
Cant build on own as my Visual Studio doesnt support it. Anyways thank you.

**Comment by dkgv** [comment]
I see, that's too bad. All I can recommend then is whitelisting Pinpoint or alternatively disabling Norton altogether.
