### ISSUE TITLE
App Stuck on "Loading Plugins"

### ISSUE THREAD

**Issue by Dylan-Weber** [dkgv/pinpoint#133]
When opening pinpoint on my machine, the search bar is stuck displaying "Loading plugins..." Settings can still be opened and closed, and the search bar can be dragged, opened and closed using the hotkey "Alt + Space," but nothing can be typed into the bar.

My Specs:
Processor:	AMD Ryzen 5 2600X Six-Core Processor              3.60 GHz
Installed RAM:	16.0 GB
System type:	64-bit operating system, x64-based processor

Edition	Windows 10 Home
Version	20H2
OS build	19042.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by Dylan-Weber** [comment]
It seems like this issue goes away when I comment out the lines `// Model.PluginEngine.AddPlugin(new AppSearchPlugin()),` and `Model.PluginEngine.AddPlugin(new TranslatePlugin()),` in MainWindows.xaml.cs.

I'm not too familiar with C# (besides Unity), so I was unable to actually get debug output when running through dotnet run. If anyone could teach me how, that would be great! Thank you :)

**Comment by Dylan-Weber** [comment]
These seem to be the problems:

```
Exception thrown: 'System.IndexOutOfRangeException' in Pinpoint.Plugin.AppSearch.dll
Exception thrown: 'System.IndexOutOfRangeException' in System.Private.CoreLib.dll
```

**Comment by dkgv** [comment]
Thanks!

I opened #135 to cover the more general issue of `TryLoad` causing loading to stall
