### ISSUE TITLE
Bookmarks plugin: FirefoxBookmarkExtractor doesn't include alternate firefox installs

### ISSUE THREAD

**Issue by mgrandi** [dkgv/pinpoint#155]
I use firefox nightly as my default browser, and it seems that the bookmarks plugin doesn't include any of my bookmarks

I looked at the source code for the bookmarks plugin:

https://github.com/dkgv/pinpoint/blob/75c8cbc960d94f1dc26d6275f260ec9e2c255d78/Pinpoint.Plugin.Bookmarks/FirefoxBookmarkExtractor.cs#L58-L79

and it seems the problem is that it is using the first profile that shows up in the directory listing, but that doesn't take into account the case that a user has multiple firefox installations or multiple profiles (and one installation). As of firefox 67, there is a new profile created per "flavor" of firefox:

https://support.mozilla.org/en-US/kb/dedicated-profiles-firefox-installation
https://support.mozilla.org/en-US/kb/understanding-depth-profile-installation

![image](https://user-images.githubusercontent.com/802786/186481797-29f9b1f3-356e-40ff-a7e0-836ef83d0ea4.png)

it talks about how there are separate profiles for "Normal" firefox, Nightly, Beta, Developer Edition, and Extended Support Release (ESR) versions now too, but there are also "old" profile folders that don't have anything in them (my old one `1jyccrk5.default`, just has a single file left in it after it was migrated to the `pcb5iwyk.default-release` profile

A simple way to fix this is to make it so that every directory in Profiles is parsed for bookmarks, or an alternate way is to parse 
`C:\Users\USER\AppData\Roaming\Mozilla\Firefox\installs.ini` and `C:\Users\USER\AppData\Roaming\Mozilla\Firefox.profiles.ini` to figure out what profiles to parse. `installs.ini` shows the "hash" of each install, and then you can look it up in `profiles.ini` by looking for `[Install<HASHHERE>]` entries

examples:

install.ini:

```ini
[308046B0AF4A39CB]
Default=Profiles/pcb5iwyk.default-release
Locked=1

[6F193CCC56814779]
Default=Profiles/ce7f2nr1.default-nightly
Locked=1


```

profiles.ini:

```ini
[Install308046B0AF4A39CB]
Default=Profiles/pcb5iwyk.default-release
Locked=1

[Profile2]
Name=default-nightly
IsRelative=1
Path=Profiles/ce7f2nr1.default-nightly

[Profile1]
Name=default
IsRelative=1
Path=Profiles/1jyccrk5.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=Profiles/pcb5iwyk.default-release

[Install6F193CCC56814779]
Default=Profiles/ce7f2nr1.default-nightly
Locked=1

[General]
StartWithLastProfile=1
Version=2

[BackgroundTasksProfiles]
MozillaBackgroundTask-6F193CCC56814779-backgroundupdate=rcfkzsfo.MozillaBackgroundTask-6F193CCC56814779-backgroundupdate


```

**Comment by dkgv** [comment]
Thanks for providing such a descriptive explanation 👍
