### ISSUE TITLE
Color Hexcode/RGB-code determinator

### ISSUE THREAD

**Issue by DanielDKnudsen** [dkgv/pinpoint#45]
Desired flow: 
- Click color-picker button
- Click on pixel on screen you want to get Hexcode/RGB-code for
- Clipboard code
-

**Comment by DanielDKnudsen** [comment]
What's thje status on this - I really need to get dem colours you know

**Comment by dkgv** [comment]
I don't see how this can be fitted into the general flow of Pinpoint :(
